### ISSUE TITLE
Fix PIR term shrinking

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6129] opened 2024-05-24 13:25 UTC
Shrinking is sometimes slow because a large number of shrinks are generated. See [this comment](https://github.com/input-output-hk/plutus/pull/4949#discussion_r1029985014).

There was a test failure on prop_shrinkTermSound : 
```
    prop_shrinkTermSound:                               FAIL
      *** Failed! Falsified (after 3 tests and 3 shrinks):
      ty,tm = ( integer -> d4_4
      , let data d4_4 | m2_2 where
              
        in error {integer -> d4_4} )
      [ E019: Error during PIR typechecking:
      Free type variable at  () :  d4
      , E019: Error during PIR typechecking:
      Free type variable at  () :  d4
      , E019: Error during PIR typechecking:
      Free type variable at  () :  d4 ]
      Use --quickcheck-replay=257544 to reproduce.
      Use -p '/prop_shrinkTermSound/' to rerun this test only.
```
[Link to full log](https://ci.zw3rk.com/log/3nrpp31y124xvslhdb2pyxg3736xi4yb-plutus-core-test-plutus-ir-test-1.1.1.0-check.drv)

**Comment by effectfully** [comment] 2024-06-18 23:22
Duplicate of #5981.

**Closed by effectfully** 2024-06-18 23:22 UTC
Labels: Internal
