### ISSUE TITLE
Add user-specified options to the Plutus Tx plugin

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6101] opened 2024-05-24 10:35 UTC
See discussion here: https://github.com/input-output-hk/plutus/issues/5194 

The interface we were settling on was something like this:

Add a special function queryUserFlag (forall opt :: Symbol) :: BuiltinBool

The compiler should recognize this function (we can’t compile it normally anyway because of the type-level strings), and compile it into true/false depending on whether the corresponding -fplugin-opt PlutusTx.Plugin:user-flag=whatever is set

(name bikeshedding possible of course)

A natural use of this is for “debug logging”: we can define

```
debugTrace :: BuiltinString -> a -> a
debugTrace s x = ifThenElse (queryOpt @"debug") (\_ -> trace s x) (\_ -> x) ()
```

More generally it enables user-controlled compile-time flags, which is quite handy.

Notes:

Note that we can also do this for some other builtin types, e.g. we could have user-defined integers or strings fairly easily. Unsure how useful that would be.

We will want `PLT-4586: Simple optimization for ifThenElse` also to ensure that the code in the dead branch gets eliminated.

**Comment by effectfully** [comment] 2024-06-19 00:58
A duplicate of #5194.

**Closed by effectfully** 2024-06-19 00:58 UTC
Labels: Internal
