### ISSUE TITLE
Spelling mistake?

### ISSUE THREAD

**Issue by perturbing** [IntersectMBO/plutus#6243] opened 2024-06-25 19:51 UTC
https://github.com/IntersectMBO/plutus/blob/bc8c3a765769d2c0cd41c43278f5954cfdfd9b15/plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs#L220

did you mean

```Haskell
-- | Similar to TxOutRef, but for GovActions
data GovernanceActionId = GovernanceActionId
  { getTxId        :: V3.TxId
  , getGovActionIx :: Haskell.Integer
  }
  deriving stock (Generic, Haskell.Show, Haskell.Eq, Haskell.Ord)
```

**Comment by effectfully** [comment] 2024-06-26 04:52
No, `gaid` is a (weird) abbreviation of `GovernanceActionId`, it's pretty common in the Haskell world to prefix fields with an abbreviation of the type due to the lack of type-based name resolution (workarounds exist, but we don't use them).

So I think this is as intended and I'm gonna close the issue as such. But thank you for double-checking!

**Closed by effectfully** 2024-06-26 04:52 UTC
Labels: status: needs triage
