### ISSUE TITLE
nix develop github:IntersectMBO/plutus

### ISSUE THREAD

**Issue by nede64** [IntersectMBO/plutus#5764] opened 2024-02-07 07:01 UTC
### Summary

hey i am following this “[Quick Start — Plutus Core and Plutus Tx User Guide 1.0.0 documentation](https://plutus.readthedocs.io/en/latest/quick-start.html)”

and the first step is
nix develop github:IntersectMBO/plutus

this gives me this error

error: builder for ‘/nix/store/qy1ldnz8fsrwxy205ly3v5hcxypi3w4s-nixpkgs-fmt-1.1.0-vendor.tar.gz.drv’ failed with exit code 1;
last 15 log lines:
unpacking sources
unpacking source archive /nix/store/3c9mzmzpmq786bb6mkjnxf71zvvjqsvr-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
source = “git+https://github.com/rust-analyzer/rowan#109885a86b7a095f637927944003add60d2f7ef3”
>
ERROR: The Cargo.lock contains git dependencies
>
This is currently not supported in the fixed-output derivation fetcher.
Use cargoLock.lockFile / importCargoLock instead.
>
For full logs, run ‘nix log /nix/store/qy1ldnz8fsrwxy205ly3v5hcxypi3w4s-nixpkgs-fmt-1.1.0-vendor.tar.gz.drv’.
error: 1 dependencies of derivation ‘/nix/store/l8jai6n0dar0q6lbbnnjqzkzvi1drxbx-nixpkgs-fmt-1.1.0.drv’ failed to build
error: 1 dependencies of derivation ‘/nix/store/7shgg8gnzadxa6z9ga89vaazrqkdczs9-plutus-env.drv’ failed to build

### Steps to reproduce the behavior

nix develop github:IntersectMBO/plutus

### Actual Result

error: builder for ‘/nix/store/qy1ldnz8fsrwxy205ly3v5hcxypi3w4s-nixpkgs-fmt-1.1.0-vendor.tar.gz.drv’ failed with exit code 1;
last 15 log lines:
unpacking sources
unpacking source archive /nix/store/3c9mzmzpmq786bb6mkjnxf71zvvjqsvr-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
source = “git+https://github.com/rust-analyzer/rowan#109885a86b7a095f637927944003add60d2f7ef3”
>
ERROR: The Cargo.lock contains git dependencies
>
This is currently not supported in the fixed-output derivation fetcher.
Use cargoLock.lockFile / importCargoLock instead.
>
For full logs, run ‘nix log /nix/store/qy1ldnz8fsrwxy205ly3v5hcxypi3w4s-nixpkgs-fmt-1.1.0-vendor.tar.gz.drv’.
error: 1 dependencies of derivation ‘/nix/store/l8jai6n0dar0q6lbbnnjqzkzvi1drxbx-nixpkgs-fmt-1.1.0.drv’ failed to build
error: 1 dependencies of derivation ‘/nix/store/7shgg8gnzadxa6z9ga89vaazrqkdczs9-plutus-env.drv’ failed to build

### Expected Result

Working nix shell 

### System info

debian 12
nix (Nix) 2.20.1

**Comment by michaelpj** [comment] 2024-02-07 10:41
Cannot reproduce. @zeme-wana any ideas?

**Comment by zeme-wana** [comment] 2024-03-14 12:29
You're building `nixpkgs-fmt-1.1.0` from source which means that your caches aren't working. 
You can confirm this by looking at the logs, you should see this line:
```
warning: ignoring untrusted substituter 'https://cache.iog.io/', you are not a trusted user.
```
Please follow [this guide](https://github.com/input-output-hk/iogx/blob/main/doc/nix-setup-guide.md) and try again.

As to why `nixpkgs-fmt-1.1.0` fails to build from source, I'm not sure. It could have to do with your nix version or nix configuration. 

I will bump `nixpkgs-fmt` to version `1.3.0` in an attempt to fix this.

**Comment by effectfully** [comment] 2024-03-14 19:16
Thanks @zeme-wana!

> Please follow [this guide](https://github.com/input-output-hk/iogx/blob/main/doc/nix-setup-guide.md) and try again.

Given this, I'm going to triage this issue as "needs info from the reporter".

**Comment by effectfully** [comment] 2024-06-19 01:03
I'm closing the issue given that there's been no info from the reported for more than three months. Do feel free to reopen.

**Closed by effectfully** 2024-06-19 01:03 UTC
Labels: bug, status: needs info from the reporter
